---
title: "Anotación"
author: "Laura Monleón Vicente"
format: html
lang: es
date: today
execute: 
  eval: true
  error: true
engine: knitr
bibliography: ../../doc/references.bib
format: html
editor: visual
---
## Introducción

En esta práctica vamos a trabajar con los resultados de la anotación estructural realizada sobre el ensamblaje de la práctica anterior. Desafortunadamente, los ordenadores virtuales no están preparados para realizar la anotación. Pero a continuación se muestran las órdenes que en un terminal de Bash producirían los resultados. Estas órdenes se supone que son ejecutadas desde una carpeta results/2026-04-21.

## Datos

Las secuencias que vamos a anotar son el ensamblaje obtenido en la práctica anterior, que voy a suponer que se encuentran en una carpeta results/2026-04-16.

Las evidencias que usaremos para encontrar los genes són secuencias de proteínas que esperamos encontrar codificadas en los cóntigos. Normalmente usaríamos las proteínas conocidas de alguna especie próxima. Usaremos las 6023 proteínas que sabemos que codifica el cromosoma 4 de Arabidopsis thalina. Las podéis descargar de Uniprot

## Resultados
# Modificación de los nombres de las proteínas
# Ejercicio 1

Sabiendo que una forma de hacerlo es la siguiente, incluye la orden en un bloque de Bash de tu documento de Quarto de tal manera que el archivo de entrada esté en tu carpeta data y el de salida en la misma carpeta de trabajo de la práctica actual, y además, que sólo se ejecute si el archivo de salida proteinas.fasta no existe.

```{bash}
if [ ! -e proteinas.fasta ]; then
   awk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}' ../../data/uniprotkb.fasta > proteinas.fasta
fi
```

## Análisis de los resultados de RepeatModeler
RepeatModeler fue ejecutado de la manera siguiente:

```{bash}
# Paso previo para convertir el ensamblaje en una base de datos de BLAST:
BuildDatabase -name At4 ../2026-04-16/asm1/At4.fa

RepeatModeler -database At4 -threads 6 >& run.log
```

.
├── At4-families.fa               
├── At4-families.stk   
├── At4.nhr                     
├── At4.nin                           
├── At4.njs                           
├── At4.nnd                              
├── At4.nni               
├── At4.nog              
├── At4.nsq              
├── At4-rmod.log
├── At4.translation 
├── RM_358880.MonApr202033152026
│   ├── consensi.fa
│   ├── families.stk
│   ├── genome.2bit
│   ├── rmod.log
│   ├── round-1
│   ├── round-2
│   └── round-3
└── run.log

Nota: los resultados un nivel por debajo de "RM_358880.MonApr202033152026" no han salido ya que ha habido un error desde el archivo que nos ha proporcionado el profesor.

# Ejercicio 2

Explora los resultados de RepeatModeler y trata de contestar las preguntas siguientes.

    ¿Cuántas familias de elementos transponibles se han encontrado?
```{bash}
grep -c "^>" RepeatModelerResults/At4-families.fa
```
Cada familia corresponde a una secuencia en formato FASTA, por lo tanto, basta contar cuántas cabeceras (>) hay. El número obtenid, 24, se corresponde con el número de familias de elementos transponibles.

    ¿Cuánto duró la ejecución del programa?
```{bash}
grep -i "start" RepeatModelerResults/run.log
grep -i "end" RepeatModelerResults/run.log
```
```{bash}
less RepeatModelerResults/run.log
```
La ejecución del programa duró 1 hora, 2 minutos y 16 segundos.

    ¿Cuál dirías que es el archivo de salida más importante?
At4-families.fa

El archivo de salida más importante es At4-families.fa, ya que contiene las secuencias consenso de las familias de elementos repetitivos identificadas. Este archivo constituye la base para análisis posteriores, como la anotación de repeticiones en el genoma mediante herramientas como RepeatMasker.

En el archuivo llamado stk que es el alineamiento de estocolmo tendrá unas cuantas secuencias de familias alineadas para generar el consenso. Si representamos en diagramas de cajas los tipos de familias vemos que existen diferentes tipos de elementos disponibles que se recogen en RepeatModeler como por ejemplo loselementos LINEs o Los Gypsy.

##  Suavizar la máscara
RepeatMasker fue ejecutado así:
```{bash}
RepeatMasker -lib At4-families.fa -dir RM01 -gtf ../../data/At4.fa
```

Podríamos haber aplicado el RepeatMasker directamente con todos los elementos transponibles de Arabidopsis Thaliana porque estos ya se conocen pero los hemos generado nosotros para saber cómo hacerlo. 

En repeatMasker, no ha conseguido hacer un enmascaramiento suave, al ser duro, veremos que los elementos tranonibles aparecen indicados con "N" en vez de indicar el nucleótido en letras minúsculas. El archivo generado .gff nos dice las coorddenadas en las que se encuentra cada instancia de elemento transponible. Esto se lo hemos tenido que pedir, una vez tenemos este ensamblaje enmascarado de forma suave ya podemos ejecutar GALBA. 

#Ejercicio 3

 Instala el programa bedtools siguiendo las instrucciones oportunas para tu sistema en la página oficial. Utiliza el ensamblaje original como archivo FASTA de entrada y el archivo GFF que ha producido RepetaMasker como coordenadas de las regiones a enmascarar. Lee el manual de bedtools maskfasta en este enlace y genera el ensamblaje con máscara suave llamado At4.soft.fa.

```{bash}
export PATH=$PATH:~/bin/bedtools2/bin
bedtools maskfasta -fi ../2026-04-16/asm1/At4.fa \
-fo At4.soft.fa \
-bed RepeatMaskerResults/RM01/At4.fa.out.gff \
-soft
```
    
## GALBA

Para ejecutar GALBA ha sido necesario crear algunas variables de entorno que indican donde puede GALBA encontrar un par de ejecutables más. Para facilitar la reproducibilidad, este tipo de definiciones deben aparecer al principio del bloque, donde son más visibles, para que sean fácilmente modificadas cuando las órdenes vayan a ejecutarse en otro ordenador.

GALBA es un script de PEARL que está olvidad por la mayoría de personas pero todavía se puede utilizar. Ellos no se dan mucha importancia a si mismos porque piensan que hay programas mejor que ellos como BREAKER, antes que instalar GALBA2 instalaríamos SINGULARITI Para esto es muy posible que exista un programa de inteligencia Artificial como ALphaPhold parapredecir la estructura de proteinas. 

```{bash}
export TSEBRA_PATH=/home/joiglu/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=/home/joiglu/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta
```

# Ejercicio 4

Incluye en tu documento de Quarto un bloque de código (pero no ejecutable, con la opción eval: false) como el anterior, donde los caminos TSERBA y a MINIPROTHINT se correspondan con tu propia carpeta bin, aunque no los tengas instalados.
```{bash}
```{bash eval=false}
export TSEBRA_PATH=$HOME/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=$HOME/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta
```
 
Para garantizar la reproducibilidad del análisis, se definen al inicio del bloque las variables de entorno necesarias para que GALBA localice las herramientas auxiliares requeridas (TSEBRA y miniprothint). Se emplean rutas relativas al directorio HOME del usuario para facilitar la portabilidad del código entre distintos sistemas.

Encontrarás los resultados de GALBA en la carpeta comprimida galba.zip, en el aula virtual.

# Ejercicio 5

Échales un vistazo a los archivos de salida de GALBA y trata de sacar algo en claro.

El archivo más importante es GALBA.gtf que es el cóntigo. me dice donde empieza, donde termina, una puntuación, la cadena directa o inversa y donde lo ha encontrado y al final un poco de información sobre si es un exón, intron, a qué gen pertenece. Nos ofrece mucha información, una predicción exacta de la secuencia codificante. Es fundamental esta información.

Además, se han generado archivos intermedios importantes como hintsfile.gff, que recoge las pistas derivadas de alineamientos proteína-genoma utilizadas para guiar la predicción, y miniprot_trainingGenes.gtf, que contiene los genes empleados para entrenar el modelo. El archivo prot_seq_all.fa recoge las proteínas predichas a partir de la anotación.

La estructura de carpetas, incluyendo archive y errors, refleja el funcionamiento interno del pipeline, almacenando tanto los resultados intermedios como los registros de ejecución. En conjunto, estos resultados indican que GALBA ha producido una anotación genómica completa que puede utilizarse para estudios funcionales y comparativos.

